apiVersion: v1
kind: Pod
metadata:
	name: db
spec:
	containers:
		- name: db
		  image: 311335618943.dkr.ecr.us-east-1.amazonaws.com/amehta63-db:v1.0
		  env:
			- name: MYSQL_ROOT_PASSWORD
			  value: pw
		  ports:
			- containerPort: 3306
		