apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: wapp-replicaset
  namespace: wappns
  labels:
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: wapp
        image: 311335618943.dkr.ecr.us-east-1.amazonaws.com/amehta63-wapp:v2.0
        env:
        - name: DBHOST
          value: "10.244.0.13"
        - name: MYSQL_ROOT_PASSWORD
          value: pw
        - name: DBUSER
          value: root
        - name: DBPWD
          value: pw
        - name: DBPORT
          value: "3306"
        ports:
        - containerPort: 8080
          protocol: TCP