apiVersion: apps/v1
kind: ReplicaSet

metadata:
	name: wapp-replicaset
	namespace: wappns
	labels:
	  tier: development
	  name: wapp

spec:
	replicas:3
	selector:
	  matchLabels:
	    type: web
	    app: wapp
	template:
	  metadata:
 	    name: wapp
            namespace: wappns
          spec:
            containers:
            - name: wapp
              image: 311335618943.dkr.ecr.us-east-1.amazonaws.com/amehta63-wapp:v2.0
              env:
              - name: DBHOST
                value: "10.244.0.7"
              - name: MYSQL_ROOT_PASSWORD
                value: pw
              - name: DBUSER
                value: root
              - name: DBPWD
                value: pw
              - name: DBPORT
                value: "3306"
             ports:
             - containerPort: 8080
	