apiVersion: v1

kind: Service

metadata:
  name: wappn
  namespace: wappns
  labels:
    app: wapp
spec:
  type: NodePort
  selector:
    app: wapp
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  